name: YetiMap
main: net.yeticraft.xxtraineexx.YetiMap.YetiMap
version: 2.3
description: >
             YetiMap
commands:
  map:
    description: Type /map <yeticraft/nether/reset> to show a full size map or reset your current map.
permissions:
  yetimap.create:
    description: Create a yeticraft map image
    default: op
  yetimap.nolines:
    description: Create a yeticraft map image w/no lines
    default: op