name: YetiMap
main: YetiMap.YetiMap
version: 1.1
description: >
             YetiMap
commands:
  map:
    description: Interact with the YetiMap plugin
    usage: "Usage: '/map [yeticraft, nether, the_end, reset]'"